// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-LAv8HK1Qlh7KbxrBpEiXMdbaoF6QvNA',
    appId: '1:124291174150:web:65ac340ec0ba3ec8ca1887',
    messagingSenderId: '124291174150',
    projectId: 'time-management-ase456',
    authDomain: 'time-management-ase456.firebaseapp.com',
    storageBucket: 'time-management-ase456.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfE52S8XxGkP7xbu3jxlYAMqzYAmQpNEI',
    appId: '1:124291174150:android:f4c25fa76fcf7f09ca1887',
    messagingSenderId: '124291174150',
    projectId: 'time-management-ase456',
    storageBucket: 'time-management-ase456.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-LAv8HK1Qlh7KbxrBpEiXMdbaoF6QvNA',
    appId: '1:124291174150:web:edeb85fda7ab7b27ca1887',
    messagingSenderId: '124291174150',
    projectId: 'time-management-ase456',
    authDomain: 'time-management-ase456.firebaseapp.com',
    storageBucket: 'time-management-ase456.appspot.com',
  );
}
